AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Smykowski - AI Project Coordinator for GitHub (Built on Schrute)

Parameters:
  GitHubRepository:
    Type: String
    Description: GitHub repository (owner/repo)

  GitHubToken:
    Type: String
    Description: GitHub Personal Access Token
    NoEcho: true

  GitHubWebhookSecret:
    Type: String
    Description: GitHub Webhook Secret
    NoEcho: true

  ClaudeAPIKey:
    Type: String
    Description: Anthropic Claude API Key
    NoEcho: true

  TeamLeadEmail:
    Type: String
    Description: Team lead email for escalations

  SlackBotToken:
    Type: String
    Description: Slack Bot User OAuth Token
    NoEcho: true
    Default: ''

  SlackSigningSecret:
    Type: String
    Description: Slack App Signing Secret
    NoEcho: true
    Default: ''

Globals:
  Function:
    Timeout: 120
    MemorySize: 1024
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_ENV: production
        GITHUB_REPOSITORY: !Ref GitHubRepository
        TEAM_LEAD_EMAIL: !Ref TeamLeadEmail

Resources:
  # ============================================================================
  # DynamoDB Tables
  # ============================================================================

  CommitmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-commitments'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: person_email
          AttributeType: S
        - AttributeName: deadline
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: person_email-index
          KeySchema:
            - AttributeName: person_email
              KeyType: HASH
            - AttributeName: deadline
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true

  TeamStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-team-state'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  MetricsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-metrics'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: metric_id
          AttributeType: S
      KeySchema:
        - AttributeName: metric_id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  ProcessesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-processes'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: process_id
          AttributeType: S
        - AttributeName: repo_id
          AttributeType: S
      KeySchema:
        - AttributeName: process_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: repo_id-index
          KeySchema:
            - AttributeName: repo_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true

  IssueMetricsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-issue-metrics'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: issue_id
          AttributeType: S
        - AttributeName: repo_id
          AttributeType: S
      KeySchema:
        - AttributeName: issue_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: repo_id-index
          KeySchema:
            - AttributeName: repo_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true

  SlackEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-slack-events'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true

  # ============================================================================
  # Secrets Manager
  # ============================================================================

  GitHubTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}/github-token'
      SecretString: !Ref GitHubToken

  GitHubWebhookSecretSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}/github-webhook-secret'
      SecretString: !Ref GitHubWebhookSecret

  ClaudeAPIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}/claude-api-key'
      SecretString: !Ref ClaudeAPIKey

  SlackBotTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}/slack-bot-token'
      SecretString: !Ref SlackBotToken

  SlackSigningSecretSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}/slack-signing-secret'
      SecretString: !Ref SlackSigningSecret

  # ============================================================================
  # Lambda Functions
  # ============================================================================

  EmailProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: lambdas/email-processor/index.handler
      Environment:
        Variables:
          COMMITMENTS_TABLE: !Ref CommitmentsTable
          TEAM_STATE_TABLE: !Ref TeamStateTable
          GITHUB_TOKEN_SECRET: !Ref GitHubTokenSecret
          CLAUDE_API_KEY_SECRET: !Ref ClaudeAPIKeySecret
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CommitmentsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TeamStateTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref GitHubTokenSecret
                - !Ref ClaudeAPIKeySecret

  GitHubWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: lambdas/github-webhook/index.handler
      Environment:
        Variables:
          COMMITMENTS_TABLE: !Ref CommitmentsTable
          TEAM_STATE_TABLE: !Ref TeamStateTable
          PROCESSES_TABLE: !Ref ProcessesTable
          ISSUE_METRICS_TABLE: !Ref IssueMetricsTable
          GITHUB_TOKEN_SECRET: !Ref GitHubTokenSecret
          GITHUB_WEBHOOK_SECRET: !Ref GitHubWebhookSecretSecret
          CLAUDE_API_KEY_SECRET: !Ref ClaudeAPIKeySecret
      Events:
        WebhookApi:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CommitmentsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TeamStateTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ProcessesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref IssueMetricsTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref GitHubTokenSecret
                - !Ref GitHubWebhookSecretSecret
                - !Ref ClaudeAPIKeySecret

  SchedulerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: lambdas/scheduler/index.handler
      Environment:
        Variables:
          COMMITMENTS_TABLE: !Ref CommitmentsTable
          TEAM_STATE_TABLE: !Ref TeamStateTable
          METRICS_TABLE: !Ref MetricsTable
          GITHUB_TOKEN_SECRET: !Ref GitHubTokenSecret
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CommitmentsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TeamStateTable
        - DynamoDBCrudPolicy:
            TableName: !Ref MetricsTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref GitHubTokenSecret

  WikiMonitorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: lambdas/wiki-monitor/index.handler
      Timeout: 180
      Environment:
        Variables:
          PROCESSES_TABLE: !Ref ProcessesTable
          GITHUB_TOKEN_SECRET: !Ref GitHubTokenSecret
          CLAUDE_API_KEY_SECRET: !Ref ClaudeAPIKeySecret
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProcessesTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref GitHubTokenSecret
                - !Ref ClaudeAPIKeySecret

  PRReviewReminderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: lambdas/pr-review-reminder/index.handler
      Timeout: 180
      Environment:
        Variables:
          TEAM_STATE_TABLE: !Ref TeamStateTable
          ISSUE_METRICS_TABLE: !Ref IssueMetricsTable
          GITHUB_TOKEN_SECRET: !Ref GitHubTokenSecret
          CLAUDE_API_KEY_SECRET: !Ref ClaudeAPIKeySecret
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 ? * MON-FRI *)
            Description: Check for stale PRs weekdays at 9am UTC
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TeamStateTable
        - DynamoDBCrudPolicy:
            TableName: !Ref IssueMetricsTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref GitHubTokenSecret
                - !Ref ClaudeAPIKeySecret

  StatusReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: lambdas/status-report/index.handler
      Timeout: 240
      Environment:
        Variables:
          COMMITMENTS_TABLE: !Ref CommitmentsTable
          TEAM_STATE_TABLE: !Ref TeamStateTable
          METRICS_TABLE: !Ref MetricsTable
          ISSUE_METRICS_TABLE: !Ref IssueMetricsTable
          GITHUB_TOKEN_SECRET: !Ref GitHubTokenSecret
          CLAUDE_API_KEY_SECRET: !Ref ClaudeAPIKeySecret
      Events:
        WeeklySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 ? * MON *)
            Description: Generate weekly status report every Monday at 10am UTC
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CommitmentsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TeamStateTable
        - DynamoDBCrudPolicy:
            TableName: !Ref MetricsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref IssueMetricsTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref GitHubTokenSecret
                - !Ref ClaudeAPIKeySecret

  SlackWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: lambdas/slack-webhook/index.handler
      Timeout: 30
      Environment:
        Variables:
          SLACK_EVENTS_TABLE: !Ref SlackEventsTable
          SLACK_SIGNING_SECRET: !Ref SlackSigningSecretSecret
      Events:
        WebhookApi:
          Type: Api
          Properties:
            Path: /slack/events
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SlackEventsTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref SlackSigningSecretSecret

  SlackProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: lambdas/slack-processor/index.handler
      Timeout: 180
      MemorySize: 1024
      Environment:
        Variables:
          SLACK_EVENTS_TABLE: !Ref SlackEventsTable
          SLACK_BOT_TOKEN_SECRET: !Ref SlackBotTokenSecret
          GITHUB_TOKEN_SECRET: !Ref GitHubTokenSecret
          CLAUDE_API_KEY_SECRET: !Ref ClaudeAPIKeySecret
          GITHUB_REPOSITORY: !Ref GitHubRepository
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Description: Process Slack events every 5 minutes
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SlackEventsTable
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref SlackBotTokenSecret
                - !Ref GitHubTokenSecret
                - !Ref ClaudeAPIKeySecret

Outputs:
  WebhookUrl:
    Description: GitHub Webhook URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook'

  SlackWebhookUrl:
    Description: Slack Events URL (configure in Slack app settings)
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/slack/events'

  CommitmentsTableName:
    Description: Commitments DynamoDB Table
    Value: !Ref CommitmentsTable

  TeamStateTableName:
    Description: Team State DynamoDB Table
    Value: !Ref TeamStateTable

  ProcessesTableName:
    Description: Processes DynamoDB Table
    Value: !Ref ProcessesTable

  IssueMetricsTableName:
    Description: Issue Metrics DynamoDB Table
    Value: !Ref IssueMetricsTable

  SlackEventsTableName:
    Description: Slack Events DynamoDB Table
    Value: !Ref SlackEventsTable
