import type { ScheduledEvent } from 'aws-lambda'
import { GitHubService } from '~/lib/github/index.js'
import { ClaudeClient } from '@schrute/lib/claude/client.js'
import { getSecret } from '../utils/secrets.js'

/**
 * Status Report Lambda Handler
 * Scheduled to run weekly (Mondays at 10am UTC)
 *
 * Responsibilities:
 * 1. Gather metrics from past week (issues closed, PRs merged, commits)
 * 2. Generate comprehensive status report
 * 3. Post report to GitHub (issue or discussion)
 */
export async function handler(event: ScheduledEvent) {
  console.log('Weekly Status Report triggered:', event.time)

  try {
    const githubToken = await getSecret(process.env.GITHUB_TOKEN_SECRET!)
    const claudeApiKey = await getSecret(process.env.CLAUDE_API_KEY_SECRET!)

    const github = new GitHubService(githubToken, process.env.GITHUB_REPOSITORY!, '')
    const claudeClient = new ClaudeClient({ apiKey: claudeApiKey })

    // Get date range for past week
    const endDate = new Date()
    const startDate = new Date(endDate.getTime() - 7 * 24 * 60 * 60 * 1000)

    console.log(`Generating report for ${startDate.toISOString()} to ${endDate.toISOString()}`)

    // Gather metrics
    const allIssues = await github.issues.list({ state: 'all' })
    const issuesClosed = allIssues.filter((issue) => {
      if (!issue.closed_at) return false
      const closedDate = new Date(issue.closed_at)
      return closedDate >= startDate && closedDate <= endDate
    })

    const openPRs = await github.pullRequests.list({ state: 'open' })
    const closedPRs = await github.pullRequests.list({ state: 'closed' })
    const prsMerged = closedPRs.filter((pr) => {
      if (!pr.merged_at) return false
      const mergedDate = new Date(pr.merged_at)
      return mergedDate >= startDate && mergedDate <= endDate
    })

    // Build status report
    const reportData = {
      week_ending: endDate.toISOString().split('T')[0],
      metrics: {
        issues_closed: issuesClosed.length,
        issues_open: allIssues.filter((i) => i.state === 'open').length,
        prs_merged: prsMerged.length,
        prs_open: openPRs.length,
      },
    }

    console.log('Report data:', JSON.stringify(reportData, null, 2))

    // Generate narrative summary using Claude
    const summaryPrompt = `Generate a concise weekly project status summary based on this data:

Week ending: ${reportData.week_ending}

Metrics:
- Issues closed: ${reportData.metrics.issues_closed}
- Open issues: ${reportData.metrics.issues_open}
- PRs merged: ${reportData.metrics.prs_merged}
- Open PRs: ${reportData.metrics.prs_open}

Provide a 2-3 paragraph summary highlighting progress, any concerns, and recommendations.`

    const summaryResponse = await claudeClient.query({
      messages: [{ role: 'user', content: summaryPrompt }],
      max_tokens: 1000,
    })

    const summary = summaryResponse.content

    // Create report markdown
    const reportMarkdown = `# Weekly Status Report - ${reportData.week_ending}

## Summary

${summary}

## Metrics

- **Issues Closed:** ${reportData.metrics.issues_closed}
- **Open Issues:** ${reportData.metrics.issues_open}
- **PRs Merged:** ${reportData.metrics.prs_merged}
- **Open PRs:** ${reportData.metrics.prs_open}

---
*Generated by Smykowski on ${new Date().toISOString()}*
`

    // Post report to GitHub as an issue
    const report = await github.issues.create({
      title: `📊 Weekly Status Report - ${reportData.week_ending}`,
      body: reportMarkdown,
      labels: ['status-report', 'weekly'],
    })

    console.log(`Created status report issue: #${report.number}`)

    return {
      statusCode: 200,
      body: JSON.stringify({
        message: 'Weekly status report generated',
        issue_number: report.number,
        metrics: reportData.metrics,
      }),
    }
  } catch (error) {
    console.log(`Error generating status report: ${error}`)
    throw error
  }
}
